### ISSUE TITLE
fednode_run.py fails if python3-appdirs not installed

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/federatednode_build#195]
```
rippler@ubuntu:~$ BRANCH=master
rippler@ubuntu:~$ wget -q -O /tmp/fednode_run.py https://raw.github.com/CounterpartyXCP/federatednode_build/${BRANCH}/run.py
rippler@ubuntu:~$ sudo python3 /tmp/fednode_run.py
[sudo] password for rippler:
Please run this script as a non-root user.
rippler@ubuntu:~$ python3 /tmp/fednode_run.py
Traceback (most recent call last):
  File "/tmp/fednode_run.py", line 65, in <module>
    delete_counterpartyd_lockfile()
  File "/tmp/fednode_run.py", line 36, in delete_counterpartyd_lockfile
    import appdirs #installed earlier
ImportError: No module named 'appdirs'
rippler@ubuntu:~$ sudo apt-cache search appdirs
python-appdirs - determining appropriate platform-specific directories (Python 2)
python3-appdirs - determining appropriate platform-specific directories (Python 3)
rippler@ubuntu:~$ sudo apt-get install python3-appdirs -y

```

**Comment by rippler** [comment]
Another one:
```
  File "numpy/core/setup.py", line 42, in check_types
 'https://github.com/gwik/geventhttpclient/archive/83ded6980a2e37025acbe5a93a52ceedd8f9338a.zip#egg=geventhttpclient-1.2.0',

  File "numpy/core/setup.py", line 293, in check_types
SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
```

**Comment by robby-dermody** [comment]
?? there is no delete_counterpartyd_lockfile function any more...is this still relevant?

if this is still an issue, can you trace it down to a part in the current fednode scripts? (I've made some updates)

**Comment by rippler** [comment]
No issues spotted in yesterday's develop branch
