### ISSUE TITLE
v1.1.0: Misconfiguration related to main CP DB name change

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/federatednode_build#223]
I just (U)pdated Fed Node 1.1.0 hoping to get the latest Bitcoin Core 0.10 (without "-rc2").

```
rippler@cpd01:~$ sudo sv stop counterparty
ok: down: counterparty: 169s
rippler@cpd01:~$ sudo ps -ef | grep party
root      1994 12233  0 08:42 ?        00:00:00 su -s /bin/bash -c /usr/local/bin/counterparty-server --testnet --config-file=${USER_HOME}/.config/counterparty/server.testnet.conf start xcpd
xcpd      1997  1994  7 08:42 ?        00:00:47 /home/xcp/federatednode_build/env/bin/python3.4 /usr/local/bin/counterparty-server --testnet --config-file=/home/xcp/.config/counterparty/server.testnet.conf start
rippler      5868 31975  0 08:52 pts/3    00:00:00 grep --color=auto party
root     12232  1052  0 Feb12 ?        00:00:00 runsv counterparty
root     12233  1052  0 Feb12 ?        00:00:00 runsv counterparty-testnet
rippler@cpd01:~$ sudo su -s /bin/bash -c 'counterparty-server reparse' xcpd
[INFO] Running v1.0.0 of counterparty-server.
[INFO] Running v9.49.4 of counterparty-lib.
[INFO] Acquiring lock.
[INFO] Connecting to database.
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.0', 'console_scripts', 'counterparty-server')()
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/server.py", line 109, in main
    force=args.force, verbose=args.verbose)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_lib-9.49.4-py3.4.egg/counterpartylib/server.py", line 318, in initialise
    db = database.get_connection(read_only=False)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_lib-9.49.4-py3.4.egg/counterpartylib/lib/database.py", line 91, in get_connection
    raise exceptions.DatabaseError('Integrity check failed.')
counterpartylib.lib.exceptions.DatabaseError: Integrity check failed.
```
Running a reparse didn't help, so I had to nuke it. 

Testnet didn't get corrupt and it's running fine, but it's name is also "new".

**Comment by rippler** [comment]
On a second thought, this isn't a Fed Node bug, so I'll close this.
