### ISSUE TITLE
[develop]: socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/federatednode_build#248]
Running develop `run.py` with `develop` branch...

```
Downloading/unpacking counterpartycli from https://github.com/CounterpartyXCP/counterparty-cli/archive/develop.zip
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 480, in urlopen
    body=body, headers=headers)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 285, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1065, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1103, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1061, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 906, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 841, in send
    self.connect()
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 136, in connect
    timeout=self.timeout,
  File "/usr/lib/python3.4/socket.py", line 491, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/_vendor/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 530, in urlopen
    raise MaxRetryError(self, url, e)
pip._vendor.requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /CounterpartyXCP/counterparty-cli/archive/develop.zip (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/download.py", line 546, in unpack_http_url
    resp = session.get(target_url, stream=True)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/_vendor/requests/sessions.py", line 395, in get
    return self.request('GET', url, **kwargs)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/_vendor/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/_vendor/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/_vendor/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
pip._vendor.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /CounterpartyXCP/counterparty-cli/archive/develop.zip (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)

Storing debug log for failure in /home/xcp/.pip/pip.log
2015-09-12 11:49:23,264|ERROR: Command failed: 'sudo su -s /bin/bash -c '/home/xcp/federatednode_build/env/bin/pip install --upgrade https://github.com/CounterpartyXCP/counterparty-cli/archive/develop.zip#egg=counterpartycli' xcp'

```

**Comment by unsystemizer** [comment]
Seems like a VM issue (related to DNS lookups). May need to close later if I can't duplicate on another hypervisor.

**Comment by robby-dermody** [comment]
yes, just a VM connection/DNS resolve issue it appears
